// Treat all models in the core model module as stable implicitly
com.sortedqueue.portfolio.core.model.**

// Treat standard Java/Kotlin library datetimes as stable
kotlinx.datetime.LocalDateTime
java.time.Instant
