build:
  maxIssues: 0
  excludeCorrectable: false
  weights:
    # If you want to configure weights for rules

complexity:
  active: true
  ComplexCondition:
    active: true
    threshold: 4
  LongMethod:
    active: true
    threshold: 60
    ignoreAnnotated:
      - 'Composable'
  LongParameterList:
    active: true
    functionThreshold: 6
    constructorThreshold: 7
    ignoreDefaultParameters: true

naming:
  active: true
  ClassNaming:
    active: true
    classPattern: '[A-Z][a-zA-Z0-9]*'
  FunctionNaming:
    active: true
    functionPattern: '[a-z][a-zA-Z0-9]*'
    excludeClassPattern: '$^'
    ignoreAnnotated:
      - 'Composable'
  VariableNaming:
    active: true
    variablePattern: '[a-z][a-zA-Z0-9]*'
  ConstructorParameterNaming:
    active: true
    parameterPattern: '[a-z][A-Za-z0-9]*'
    excludes:
      - '**/TmdbApi.kt'

performance:
  active: true
  ForEachOnRange:
    active: true
  SpreadOperator:
    active: true

style:
  active: true
  MaxLineLength:
    active: true
    maxLineLength: 150
  MagicNumber:
    active: true
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
    ignorePropertyDeclaration: true
    ignoreLocalVariableDeclaration: true
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotated:
      - 'Composable'
  UnusedPrivateMember:
    active: true
    ignoreAnnotated:
      - 'Preview'
